### ISSUE TITLE
adding/editing task doesn't include backspace

### ISSUE THREAD

**Issue by barzilouik** [alalfakawma/todo_list_rust#3]
platform : linux mint 19.3 x86-64
rust : 1.46 nightly
syndrom : backspace is seen as ^G and arrows are also not effective

improvements : arrows could be used along j and k, and enter also for editing.

**Comment by alalfakawma** [comment]
Hey, i've added Enter key for editing and Arrow up down also for moving up and down. About the backspace problem, I'm not sure if the keycodes for my system and yours are the same or not, but i've added a fix to it, can you update to the latest version and check it out. Cheers.
